import FTDQE.GapFreeLindbladKernelGram
import Mathlib.MeasureTheory.Integral.Bochner.ContinuousLinearMap
import Mathlib.Algebra.Star.BigOperators

/-!
# Positive Laplace Gram kernels

A finite kernel of the form
`Kᵢⱼ = ∫₀∞ w(s) exp((ωᵢ+ωⱼ)s) ds`
with nonnegative real weight is positive semidefinite. This is the finite-dimensional
Gram identity used for arbitrary admissible weights.
-/

namespace FTDQE
namespace GapFreeLindblad

open Matrix Set MeasureTheory Filter
open scoped BigOperators ComplexOrder MatrixOrder

noncomputable section

variable {ι : Type*} [Fintype ι]

/-- Laplace kernel generated by a real weight and a finite family of real frequencies. -/
def laplaceGramMatrix (w : ℝ → ℝ) (ω : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => ((∫ s in Ioi (0 : ℝ), w s * Real.exp ((ω i + ω j) * s)) : ℂ)

/-- A Laplace kernel with nonnegative weight is positive semidefinite. -/
theorem laplaceGramMatrix_posSemidef
    {w : ℝ → ℝ} {ω : ι → ℝ}
    (hw : ∀ᵐ s ∂(volume.restrict (Ioi (0 : ℝ))), 0 ≤ w s)
    (hint : ∀ i j, IntegrableOn
      (fun s => w s * Real.exp ((ω i + ω j) * s)) (Ioi 0)) :
    (laplaceGramMatrix w ω).PosSemidef := by
  classical
  rw [Matrix.posSemidef_iff_dotProduct_mulVec]
  constructor
  · ext i j
    have hreal :
        (∫ s in Ioi (0 : ℝ), w s * Real.exp ((ω j + ω i) * s)) =
          ∫ s in Ioi (0 : ℝ), w s * Real.exp ((ω i + ω j) * s) := by
      apply integral_congr_ae
      filter_upwards with s
      rw [add_comm (ω j) (ω i)]
    simp only [Matrix.conjTranspose_apply, laplaceGramMatrix]
    rw [hreal]
    simp [Complex.star_def]
  · intro z
    let q : ℝ → ℂ := fun s => ∑ i : ι, z i * (Real.exp (ω i * s) : ℂ)
    let g : ι → ι → ℝ → ℂ := fun i j s =>
      star (z i) * ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ) * z j
    have hbase (i j : ι) : IntegrableOn
        (fun s => ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ)) (Ioi 0) :=
      (hint i j).ofReal
    have hg (i j : ι) : IntegrableOn (g i j) (Ioi 0) := by
      exact ((hbase i j).const_mul (star (z i))).mul_const (z j)
    have hentry (i j : ι) :
        laplaceGramMatrix w ω i j =
          ∫ s in Ioi (0 : ℝ),
            ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ) := by
      unfold laplaceGramMatrix
      change ((∫ s in Ioi (0 : ℝ),
          w s * Real.exp ((ω i + ω j) * s)) : ℂ) =
        ∫ s in Ioi (0 : ℝ),
          ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ)
      exact (integral_ofReal
        (𝕜 := ℂ)
        (μ := volume.restrict (Ioi (0 : ℝ)))
        (f := fun s : ℝ => w s * Real.exp ((ω i + ω j) * s))).symm
    have hconst (i j : ι) :
        star (z i) * laplaceGramMatrix w ω i j * z j =
          ∫ s in Ioi (0 : ℝ), g i j s := by
      rw [hentry]
      calc
        star (z i) *
            (∫ s in Ioi (0 : ℝ),
              ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ)) * z j =
          (∫ s in Ioi (0 : ℝ),
            star (z i) * ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ)) * z j := by
              rw [integral_const_mul_of_integrable (hbase i j)]
        _ = ∫ s in Ioi (0 : ℝ),
            (star (z i) * ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ)) * z j := by
              rw [integral_mul_const_of_integrable ((hbase i j).const_mul (star (z i)))]
        _ = ∫ s in Ioi (0 : ℝ), g i j s := by rfl
    have hinner (i : ι) :
        (∑ j : ι, ∫ s in Ioi (0 : ℝ), g i j s) =
          ∫ s in Ioi (0 : ℝ), ∑ j : ι, g i j s := by
      symm
      exact integral_finsetSum Finset.univ (fun j _ => hg i j)
    have houter (i : ι) : IntegrableOn
        (fun s => ∑ j : ι, g i j s) (Ioi 0) :=
      integrable_finsetSum Finset.univ (fun j _ => hg i j)
    have hsums :
        (∑ i : ι, ∑ j : ι, ∫ s in Ioi (0 : ℝ), g i j s) =
          ∫ s in Ioi (0 : ℝ), ∑ i : ι, ∑ j : ι, g i j s := by
      calc
        (∑ i : ι, ∑ j : ι, ∫ s in Ioi (0 : ℝ), g i j s) =
            ∑ i : ι, ∫ s in Ioi (0 : ℝ), ∑ j : ι, g i j s := by
              apply Finset.sum_congr rfl
              intro i hi
              exact hinner i
        _ = ∫ s in Ioi (0 : ℝ), ∑ i : ι, ∑ j : ι, g i j s := by
              symm
              exact integral_finsetSum Finset.univ (fun i _ => houter i)
    have hpoint (s : ℝ) :
        (∑ i : ι, ∑ j : ι, g i j s) = star (q s) * (w s : ℂ) * q s := by
      let a : ι → ℂ := fun i => star (z i) * (Real.exp (ω i * s) : ℂ)
      let b : ι → ℂ := fun j => z j * (Real.exp (ω j * s) : ℂ)
      have hstarq : star (q s) = ∑ i : ι, a i := by
        simp only [q, a, star_sum, star_mul, Complex.star_def, Complex.conj_ofReal]
        apply Finset.sum_congr rfl
        intro i hi
        ac_rfl
      have hq : q s = ∑ j : ι, b j := by
        rfl
      have hterm (i j : ι) :
          g i j s = a i * (w s : ℂ) * b j := by
        have hexp :
            Real.exp ((ω i + ω j) * s) =
              Real.exp (ω i * s) * Real.exp (ω j * s) := by
          rw [← Real.exp_add]
          congr 1
          ring
        simp only [g, a, b, hexp, Complex.ofReal_mul]
        ring
      rw [hstarq, hq]
      simp only [Finset.sum_mul, Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i hi
      apply Finset.sum_congr rfl
      intro j hj
      exact hterm i j
    have hquad :
        star z ⬝ᵥ (laplaceGramMatrix w ω *ᵥ z) =
          ∫ s in Ioi (0 : ℝ), star (q s) * (w s : ℂ) * q s := by
      calc
        star z ⬝ᵥ (laplaceGramMatrix w ω *ᵥ z) =
            ∑ i : ι, ∑ j : ι,
              star (z i) * laplaceGramMatrix w ω i j * z j := by
                simp only [dotProduct, Matrix.mulVec, Finset.mul_sum]
                apply Finset.sum_congr rfl
                intro i hi
                apply Finset.sum_congr rfl
                intro j hj
                ac_rfl
        _ = ∑ i : ι, ∑ j : ι, ∫ s in Ioi (0 : ℝ), g i j s := by
              apply Finset.sum_congr rfl
              intro i hi
              apply Finset.sum_congr rfl
              intro j hj
              exact hconst i j
        _ = ∫ s in Ioi (0 : ℝ), ∑ i : ι, ∑ j : ι, g i j s := hsums
        _ = ∫ s in Ioi (0 : ℝ), star (q s) * (w s : ℂ) * q s := by
              apply integral_congr_ae
              filter_upwards with s
              exact hpoint s
    rw [hquad]
    apply integral_nonneg_of_ae
    filter_upwards [hw] with s hs
    have hsc : (0 : ℂ) ≤ (w s : ℂ) := by exact_mod_cast hs
    exact star_left_conjugate_nonneg hsc (q s)

end

end GapFreeLindblad
end FTDQE