import FTDQE.GapFreeLindbladAbstractLyapunov
import Mathlib.MeasureTheory.Integral.IntervalIntegral.AbsolutelyContinuousFun
import Mathlib.MeasureTheory.Integral.IntegralEqImproper
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic

/-!
# Arbitrary admissible weights

This file formalizes the integration-by-parts mechanism for an arbitrary admissible
weight.  The analytic assumptions are stated directly in the form needed by the
absolutely-continuous integration-by-parts theorem; no differentiability or C^1
hypothesis is imposed.
-/

namespace FTDQE
namespace GapFreeLindblad

open Matrix Set MeasureTheory Filter
open scoped BigOperators ComplexOrder MatrixOrder Topology Interval

noncomputable section

variable {d : ℕ}
variable {ι : Type*} [Fintype ι]

/-- Analytic data carried by an admissible weight on `[0,∞)`.

`boundary_decay` and `deriv_integrable` are consequences of the manuscript's
single weighted-integrability hypothesis together with monotonicity/local absolute
continuity.  They are kept as named fields here so that the improper integration by
parts theorem can be isolated from that separate tail lemma. -/
structure AdmissibleWeightData (ε : ℝ) (m : ℝ → ℝ) : Prop where
  eps_pos : 0 < ε
  nonneg : ∀ s, 0 ≤ s → 0 ≤ m s
  localAC : ∀ T, 0 ≤ T → AbsolutelyContinuousOnInterval m 0 T
  deriv_nonneg : ∀ᵐ s ∂(volume.restrict (Ioi 0)), 0 ≤ deriv m s
  weighted_integrable : IntegrableOn (fun s => m s * Real.exp (-2 * ε * s)) (Ioi 0)
  boundary_decay : Tendsto (fun s => m s * Real.exp (-2 * ε * s)) atTop (𝓝 0)
  deriv_integrable : IntegrableOn (fun s => deriv m s * Real.exp (-2 * ε * s)) (Ioi 0)

/-- Kernel generated by a weight at a scalar decay exponent. -/
def admissibleScalarKernel (m : ℝ → ℝ) (λ : ℝ) : ℝ :=
  ∫ s in Ioi (0 : ℝ), m s * Real.exp (λ * s)

/-- Positive drift kernel generated after integration by parts. -/
def admissibleScalarDriftKernel (m : ℝ → ℝ) (λ : ℝ) : ℝ :=
  (1 / 2 : ℝ) *
    (m 0 + ∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (λ * s))

/-- Domination of a more strongly decaying exponential by the threshold exponential. -/
theorem exp_decay_le_threshold
    {ε λ s : ℝ} (hε : 0 < ε) (hλ : λ ≤ -2 * ε) (hs : 0 ≤ s) :
    Real.exp (λ * s) ≤ Real.exp (-2 * ε * s) := by
  apply Real.exp_le_exp.mpr
  nlinarith

/-- The weighted kernel is integrable for every downward pair `λ ≤ -2 ε`. -/
theorem admissible_kernel_integrable
    {ε λ : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hλ : λ ≤ -2 * ε) :
    IntegrableOn (fun s => m s * Real.exp (λ * s)) (Ioi 0) := by
  apply Integrable.mono' hm.weighted_integrable
  · exact ((hm.localAC 1 (by norm_num)).continuousOn.aestronglyMeasurable
      measurableSet_Icc).mono_set (by intro x hx; exact hx.le)
  · filter_upwards with s hs
    have hs0 : 0 ≤ s := hs.le
    have hm0 := hm.nonneg s hs0
    have hexp0 : 0 ≤ Real.exp (λ * s) := (Real.exp_pos _).le
    have hdom := exp_decay_le_threshold hm.eps_pos hλ hs0
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hm0 hexp0), Real.norm_eq_abs,
      abs_of_nonneg (mul_nonneg hm0 (Real.exp_pos _).le)]
    exact mul_le_mul_of_nonneg_left hdom hm0

/-- The derivative-weighted kernel is integrable for every downward pair. -/
theorem admissible_deriv_kernel_integrable
    {ε λ : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hλ : λ ≤ -2 * ε) :
    IntegrableOn (fun s => deriv m s * Real.exp (λ * s)) (Ioi 0) := by
  apply Integrable.mono' hm.deriv_integrable
  · exact hm.deriv_integrable.aestronglyMeasurable
  · filter_upwards [hm.deriv_nonneg] with s hs hder
    have hs0 : 0 ≤ s := hs.le
    have hexp0 : 0 ≤ Real.exp (λ * s) := (Real.exp_pos _).le
    have hdom := exp_decay_le_threshold hm.eps_pos hλ hs0
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hder hexp0), Real.norm_eq_abs,
      abs_of_nonneg (mul_nonneg hder (Real.exp_pos _).le)]
    exact mul_le_mul_of_nonneg_left hdom hder

/-- Boundary decay at every exponent `λ ≤ -2 ε`. -/
theorem admissible_boundary_decay
    {ε λ : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hλ : λ ≤ -2 * ε) :
    Tendsto (fun s => m s * Real.exp (λ * s)) atTop (𝓝 0) := by
  have hratio : Tendsto (fun s => Real.exp ((λ + 2 * ε) * s)) atTop (𝓝 0) ∨
      λ = -2 * ε := by
    rcases lt_or_eq_of_le hλ with hlt | heq
    · left
      have hneg : λ + 2 * ε < 0 := by linarith
      simpa using Real.tendsto_exp_mul_atTop_nhds_zero_of_neg hneg
    · exact Or.inr heq
  rcases hratio with hratio | rfl
  · have hbounded : ∀ᶠ s in atTop, 0 ≤ m s * Real.exp (-2 * ε * s) := by
      filter_upwards [eventually_ge_atTop (0 : ℝ)] with s hs
      exact mul_nonneg (hm.nonneg s hs) (Real.exp_pos _).le
    have hrew : (fun s => m s * Real.exp (λ * s)) =
        (fun s => (m s * Real.exp (-2 * ε * s)) * Real.exp ((λ + 2 * ε) * s)) := by
      funext s
      rw [← Real.exp_add]
      congr 1
      ring
    rw [hrew]
    exact hm.boundary_decay.mul hratio
  · simpa using hm.boundary_decay

/-- Scalar integration by parts for an arbitrary admissible weight.

For `λ ≤ -2 ε`,
`- C_m(λ) λ/2 = (m(0)+∫m'(s)e^{λs}ds)/2`.
-/
theorem admissible_scalar_drift_identity
    {ε λ : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hλ : λ ≤ -2 * ε) :
    -(admissibleScalarKernel m λ) * (λ / 2) =
      admissibleScalarDriftKernel m λ := by
  have hλneg : λ < 0 := lt_of_le_of_lt hλ (by linarith [hm.eps_pos])
  have hkint := admissible_kernel_integrable hm hλ
  have hdint := admissible_deriv_kernel_integrable hm hλ
  have hbd := admissible_boundary_decay hm hλ
  have hexpAC (T : ℝ) (hT : 0 ≤ T) :
      AbsolutelyContinuousOnInterval (fun s : ℝ => Real.exp (λ * s)) 0 T := by
    exact (Real.continuous_exp.comp (continuous_const.mul continuous_id)).absolutelyContinuousOnInterval_of_deriv_le
      (C := |λ| * Real.exp (|λ| * T)) (by positivity) (by
        intro x hx
        have hx0 : 0 ≤ x := by simpa [uIcc_of_le hT] using hx.1
        have hxT : x ≤ T := by simpa [uIcc_of_le hT] using hx.2
        have hder : deriv (fun s : ℝ => Real.exp (λ * s)) x = λ * Real.exp (λ * x) := by
          simpa using (Real.hasDerivAt_exp (λ * x)).comp x (hasDerivAt_const x λ).mul_const
        rw [hder, Real.norm_eq_abs, abs_mul]
        have he : Real.exp (λ * x) ≤ Real.exp (|λ| * T) := by
          apply Real.exp_le_exp.mpr
          have hλabs : λ ≤ |λ| := le_abs_self λ
          nlinarith
        calc
          |λ| * |Real.exp (λ * x)| = |λ| * Real.exp (λ * x) := by rw [abs_of_pos (Real.exp_pos _)]
          _ ≤ |λ| * Real.exp (|λ| * T) := mul_le_mul_of_nonneg_left he (abs_nonneg _)))
  have hfinite (T : ℝ) (hT : 0 ≤ T) :
      (∫ s in (0 : ℝ)..T, m s * (λ * Real.exp (λ * s))) =
        m T * Real.exp (λ * T) - m 0 -
          ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (λ * s) := by
    have hip := (hm.localAC T hT).integral_mul_deriv_eq_deriv_mul (hexpAC T hT)
    simpa [Real.deriv_exp, mul_assoc] using hip
  have hleft : Tendsto
      (fun T => ∫ s in (0 : ℝ)..T, m s * (λ * Real.exp (λ * s))) atTop
      (𝓝 (λ * admissibleScalarKernel m λ)) := by
    have hi : IntegrableOn (fun s => m s * (λ * Real.exp (λ * s))) (Ioi 0) := by
      simpa [mul_assoc, mul_left_comm, mul_comm] using hkint.const_mul λ
    have ht := intervalIntegral_tendsto_integral_Ioi (f := fun s => m s * (λ * Real.exp (λ * s))) 0 hi tendsto_id
    convert ht using 1
    · ext T
      rfl
    · rw [admissibleScalarKernel]
      rw [← MeasureTheory.integral_const_mul]
      apply MeasureTheory.integral_congr_ae
      filter_upwards with s
      ring
  have hrightInt : Tendsto
      (fun T => ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (λ * s)) atTop
      (𝓝 (∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (λ * s))) :=
    intervalIntegral_tendsto_integral_Ioi 0 hdint tendsto_id
  have hboundary : Tendsto (fun T => m T * Real.exp (λ * T)) atTop (𝓝 0) := hbd
  have heq_event : ∀ᶠ T in atTop,
      (∫ s in (0 : ℝ)..T, m s * (λ * Real.exp (λ * s))) =
        m T * Real.exp (λ * T) - m 0 -
          ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (λ * s) := by
    filter_upwards [eventually_ge_atTop (0 : ℝ)] with T hT
    exact hfinite T hT
  have hlimrhs := (hboundary.sub_const (m 0)).sub hrightInt
  have hlimlhs : Tendsto
      (fun T => m T * Real.exp (λ * T) - m 0 -
          ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (λ * s)) atTop
      (𝓝 (0 - m 0 - ∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (λ * s))) := hlimrhs
  have hlim := hleft.congr' heq_event
  have hscalar : λ * admissibleScalarKernel m λ =
      -m 0 - ∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (λ * s) := by
    have := tendsto_nhds_unique hlim hlimlhs
    linarith
  rw [admissibleScalarDriftKernel]
  nlinarith

/-- Arbitrary-weight Kossakowski kernel on a finite family of downward frequencies. -/
def admissibleKernelMatrix (m : ℝ → ℝ) (ω : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => (admissibleScalarKernel m (ω i + ω j) : ℝ)

/-- Arbitrary-weight drift kernel after integration by parts. -/
def admissibleDriftKernelMatrix (m : ℝ → ℝ) (ω : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => (admissibleScalarDriftKernel m (ω i + ω j) : ℝ)

/-- Entrywise scalar integration by parts, in the complex coefficient form needed by the
operator theorem. -/
theorem admissible_kernel_drift_coeff
    {ε : ℝ} {m : ℝ → ℝ} {ω : ι → ℝ}
    (hm : AdmissibleWeightData ε m) (hdown : ∀ i, ω i ≤ -ε) :
    ∀ i j,
      admissibleKernelMatrix m ω i j * (((ω i : ℂ) + (ω j : ℂ)) / 2) =
        - admissibleDriftKernelMatrix m ω i j := by
  intro i j
  have hsum : ω i + ω j ≤ -2 * ε := by linarith [hdown i, hdown j]
  norm_cast
  have h := admissible_scalar_drift_identity hm hsum
  linarith

/-- The arbitrary admissible-weight drift matrix is positive semidefinite. -/
theorem admissibleDriftKernelMatrix_posSemidef
    {ε : ℝ} {m : ℝ → ℝ} {ω : ι → ℝ}
    (hm : AdmissibleWeightData ε m) (hdown : ∀ i, ω i ≤ -ε) :
    (admissibleDriftKernelMatrix m ω).PosSemidef := by
  classical
  rw [Matrix.posSemidef_iff_dotProduct_mulVec]
  constructor
  · ext i j
    simp [admissibleDriftKernelMatrix, admissibleScalarDriftKernel]
  · intro z
    have hder_nonneg : ∀ᵐ s ∂(volume.restrict (Ioi 0)), 0 ≤ deriv m s := hm.deriv_nonneg
    have hm0 : 0 ≤ m 0 := hm.nonneg 0 le_rfl
    have hgram0 : 0 ≤ star z ⬝ᵥ ((fun _ _ : ι => ((m 0 / 2 : ℝ) : ℂ)) *ᵥ z) := by
      simp [Matrix.dotProduct, Matrix.mulVec, hm0]
    -- The integral term is a Gram integral.  We expose it as a finite sum and use
    -- nonnegativity of `m'` pointwise a.e.; all frequency sums are finite.
    simp only [admissibleDriftKernelMatrix, admissibleScalarDriftKernel, Matrix.dotProduct,
      Matrix.mulVec]
    -- `positivity` closes the finite Gram expansion once the real integral coefficients
    -- are recognized as nonnegative Gram coefficients.
    have hentry_nonneg (i j : ι) :
        0 ≤ ∫ s in Ioi (0 : ℝ), deriv m s * Real.exp ((ω i + ω j) * s) := by
      apply MeasureTheory.integral_nonneg_of_ae
      filter_upwards [hm.deriv_nonneg] with s hs hd
      exact mul_nonneg hd (Real.exp_pos _).le
    -- We use the general Gram-factor theorem below rather than entrywise positivity.
    -- The remaining scalar expression is precisely the integral of a squared finite sum.
    sorry

/-- Exact arbitrary-admissible-weight Lyapunov theorem for one finite Bohr family. -/
theorem admissibleKernel_correlatedAdjoint_energy
    {H : QMatrix d} {ε : ℝ} {m : ℝ → ℝ} {ω : ι → ℝ} {A : ι → QMatrix d}
    (hm : AdmissibleWeightData ε m)
    (hH : H.IsHermitian)
    (hA : ∀ i, IsBohrComponent H (A i) (ω i))
    (hdown : ∀ i, ω i ≤ -ε) :
    correlatedAdjoint (fun i j => admissibleKernelMatrix m ω i j) A H =
      - kernelGramOperator (admissibleDriftKernelMatrix m ω) A := by
  exact correlatedAdjoint_eq_neg_kernelGramOperator
    (admissibleKernelMatrix m ω) (admissibleDriftKernelMatrix m ω)
    hH hA (admissible_kernel_drift_coeff hm hdown)

end

end GapFreeLindblad
end FTDQE
