import FTDQE.GapFreeLindbladKernelGram
import Mathlib.MeasureTheory.Integral.Bochner.ContinuousLinearMap

/-!
# Positive Laplace Gram kernels

A finite kernel of the form
`Kᵢⱼ = ∫₀∞ w(s) exp((ωᵢ+ωⱼ)s) ds`
with nonnegative real weight is positive semidefinite.  This is the finite-dimensional
Gram identity used for arbitrary admissible weights.
-/

namespace FTDQE
namespace GapFreeLindblad

open Matrix Set MeasureTheory Filter
open scoped BigOperators ComplexOrder MatrixOrder

noncomputable section

variable {ι : Type*} [Fintype ι]

/-- Laplace kernel generated by a real weight and a finite family of real frequencies. -/
def laplaceGramMatrix (w : ℝ → ℝ) (ω : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => ((∫ s in Ioi (0 : ℝ), w s * Real.exp ((ω i + ω j) * s)) : ℂ)

/-- A Laplace kernel with nonnegative weight is positive semidefinite. -/
theorem laplaceGramMatrix_posSemidef
    {w : ℝ → ℝ} {ω : ι → ℝ}
    (hw : ∀ᵐ s ∂(volume.restrict (Ioi (0 : ℝ))), 0 ≤ w s)
    (hint : ∀ i j, IntegrableOn
      (fun s => w s * Real.exp ((ω i + ω j) * s)) (Ioi 0)) :
    (laplaceGramMatrix w ω).PosSemidef := by
  classical
  rw [Matrix.posSemidef_iff_dotProduct_mulVec]
  constructor
  · ext i j
    simp [laplaceGramMatrix, Matrix.conjTranspose_apply, add_comm]
  · intro z
    let q : ℝ → ℂ := fun s => ∑ i : ι, z i * (Real.exp (ω i * s) : ℂ)
    have hentry (i j : ι) :
        laplaceGramMatrix w ω i j =
          ∫ s in Ioi (0 : ℝ),
            ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ) := by
      rw [laplaceGramMatrix]
      symm
      exact MeasureTheory.integral_complex_ofReal
    have hg (i j : ι) : IntegrableOn
        (fun s => star (z i) *
          ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ) * z j) (Ioi 0) := by
      exact ((hint i j).ofReal.const_mul (star (z i))).mul_const (z j)
    have hquad :
        star z ⬝ᵥ (laplaceGramMatrix w ω *ᵥ z) =
          ∫ s in Ioi (0 : ℝ), star (q s) * (w s : ℂ) * q s := by
      calc
        star z ⬝ᵥ (laplaceGramMatrix w ω *ᵥ z) =
            ∑ i : ι, ∑ j : ι,
              star (z i) * laplaceGramMatrix w ω i j * z j := by
                simp [Matrix.dotProduct, Matrix.mulVec, Finset.mul_sum, mul_assoc]
        _ = ∑ i : ι, ∑ j : ι,
            ∫ s in Ioi (0 : ℝ),
              star (z i) *
                ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ) * z j := by
              apply Finset.sum_congr rfl
              intro i hi
              apply Finset.sum_congr rfl
              intro j hj
              rw [hentry]
              rw [MeasureTheory.integral_const_mul, MeasureTheory.integral_mul_const]
        _ = ∫ s in Ioi (0 : ℝ),
            ∑ i : ι, ∑ j : ι,
              star (z i) *
                ((w s * Real.exp ((ω i + ω j) * s) : ℝ) : ℂ) * z j := by
              rw [MeasureTheory.integral_finsetSum]
              · intro i hi
                rw [MeasureTheory.integral_finsetSum]
                intro j hj
                exact hg i j
              · intro i hi
                exact Integrable.finset_sum _ fun j hj => hg i j
        _ = ∫ s in Ioi (0 : ℝ), star (q s) * (w s : ℂ) * q s := by
              apply MeasureTheory.integral_congr_ae
              filter_upwards with s
              simp only [q, map_sum, star_mul, star_ofReal, Finset.mul_sum, Finset.sum_mul]
              rw [Finset.sum_comm]
              apply Finset.sum_congr rfl
              intro i hi
              apply Finset.sum_congr rfl
              intro j hj
              rw [← Complex.ofReal_mul, ← Complex.ofReal_mul, ← Real.exp_add]
              congr 2
              ring
    rw [hquad]
    apply MeasureTheory.integral_nonneg_of_ae
    filter_upwards [hw] with s hs
    have hsc : (0 : ℂ) ≤ (w s : ℂ) := by exact_mod_cast hs
    exact star_left_conjugate_nonneg hsc

end

end GapFreeLindblad
end FTDQE
