import FTDQE.GapFreeLindbladAbstractLyapunov
import Mathlib.MeasureTheory.Integral.IntervalIntegral.AbsolutelyContinuousFun
import Mathlib.MeasureTheory.Integral.IntegralEqImproper
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic

/-!
# Arbitrary admissible weights

This file formalizes the integration-by-parts mechanism for an arbitrary admissible
weight. The analytic assumptions are stated directly in the form needed by the
absolutely-continuous integration-by-parts theorem; no differentiability or C^1
hypothesis is imposed.
-/

namespace FTDQE
namespace GapFreeLindblad

open Matrix Set MeasureTheory Filter
open scoped BigOperators ComplexOrder MatrixOrder Topology Interval

noncomputable section

variable {d : ℕ}
variable {ι : Type*} [Fintype ι]

/-- Analytic data carried by an admissible weight on `[0,∞)`.

`boundary_decay` and `deriv_integrable` are consequences of the manuscript's
single weighted-integrability hypothesis together with monotonicity/local absolute
continuity. They are kept as named fields here so that the improper integration by
parts theorem can be isolated from that separate tail lemma. -/
structure AdmissibleWeightData (ε : ℝ) (m : ℝ → ℝ) : Prop where
  eps_pos : 0 < ε
  nonneg : ∀ s, 0 ≤ s → 0 ≤ m s
  localAC : ∀ T, 0 ≤ T → AbsolutelyContinuousOnInterval m 0 T
  deriv_nonneg : ∀ᵐ s ∂(volume.restrict (Ioi 0)), 0 ≤ deriv m s
  weighted_integrable : IntegrableOn (fun s => m s * Real.exp (-2 * ε * s)) (Ioi 0)
  boundary_decay : Tendsto (fun s => m s * Real.exp (-2 * ε * s)) atTop (𝓝 0)
  deriv_integrable : IntegrableOn (fun s => deriv m s * Real.exp (-2 * ε * s)) (Ioi 0)

/-- Kernel generated by a weight at a scalar decay exponent. -/
def admissibleScalarKernel (m : ℝ → ℝ) (lam : ℝ) : ℝ :=
  ∫ s in Ioi (0 : ℝ), m s * Real.exp (lam * s)

/-- Positive drift kernel generated after integration by parts. -/
def admissibleScalarDriftKernel (m : ℝ → ℝ) (lam : ℝ) : ℝ :=
  (1 / 2 : ℝ) *
    (m 0 + ∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (lam * s))

/-- Domination of a more strongly decaying exponential by the threshold exponential. -/
theorem exp_decay_le_threshold
    {ε lam s : ℝ} (hε : 0 < ε) (hlam : lam ≤ -2 * ε) (hs : 0 ≤ s) :
    Real.exp (lam * s) ≤ Real.exp (-2 * ε * s) := by
  apply Real.exp_le_exp.mpr
  nlinarith

/-- The weighted kernel is integrable for every downward pair `lam ≤ -2 ε`. -/
theorem admissible_kernel_integrable
    {ε lam : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hlam : lam ≤ -2 * ε) :
    IntegrableOn (fun s => m s * Real.exp (lam * s)) (Ioi 0) := by
  apply Integrable.mono' hm.weighted_integrable
  · exact hm.weighted_integrable.aestronglyMeasurable
  · filter_upwards with s hs
    have hs0 : 0 ≤ s := hs.le
    have hm0 := hm.nonneg s hs0
    have hexp0 : 0 ≤ Real.exp (lam * s) := (Real.exp_pos _).le
    have hdom := exp_decay_le_threshold hm.eps_pos hlam hs0
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hm0 hexp0), Real.norm_eq_abs,
      abs_of_nonneg (mul_nonneg hm0 (Real.exp_pos _).le)]
    exact mul_le_mul_of_nonneg_left hdom hm0

/-- The derivative-weighted kernel is integrable for every downward pair. -/
theorem admissible_deriv_kernel_integrable
    {ε lam : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hlam : lam ≤ -2 * ε) :
    IntegrableOn (fun s => deriv m s * Real.exp (lam * s)) (Ioi 0) := by
  apply Integrable.mono' hm.deriv_integrable
  · exact hm.deriv_integrable.aestronglyMeasurable
  · filter_upwards [hm.deriv_nonneg] with s hs hder
    have hs0 : 0 ≤ s := hs.le
    have hexp0 : 0 ≤ Real.exp (lam * s) := (Real.exp_pos _).le
    have hdom := exp_decay_le_threshold hm.eps_pos hlam hs0
    rw [Real.norm_eq_abs, abs_of_nonneg (mul_nonneg hder hexp0), Real.norm_eq_abs,
      abs_of_nonneg (mul_nonneg hder (Real.exp_pos _).le)]
    exact mul_le_mul_of_nonneg_left hdom hder

/-- Boundary decay at every exponent `lam ≤ -2 ε`. -/
theorem admissible_boundary_decay
    {ε lam : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hlam : lam ≤ -2 * ε) :
    Tendsto (fun s => m s * Real.exp (lam * s)) atTop (𝓝 0) := by
  rcases lt_or_eq_of_le hlam with hlt | heq
  · have hneg : lam + 2 * ε < 0 := by linarith
    have hratio : Tendsto (fun s => Real.exp ((lam + 2 * ε) * s)) atTop (𝓝 0) := by
      simpa using Real.tendsto_exp_mul_atTop_nhds_zero_of_neg hneg
    have hrew : (fun s => m s * Real.exp (lam * s)) =
        (fun s => (m s * Real.exp (-2 * ε * s)) * Real.exp ((lam + 2 * ε) * s)) := by
      funext s
      rw [← Real.exp_add]
      congr 1
      ring
    rw [hrew]
    exact hm.boundary_decay.mul hratio
  · rw [heq]
    exact hm.boundary_decay

/-- Scalar integration by parts for an arbitrary admissible weight.

For `lam ≤ -2 ε`,
`- C_m(lam) lam/2 = (m(0)+∫m'(s)e^{lam s}ds)/2`.
-/
theorem admissible_scalar_drift_identity
    {ε lam : ℝ} {m : ℝ → ℝ}
    (hm : AdmissibleWeightData ε m) (hlam : lam ≤ -2 * ε) :
    -(admissibleScalarKernel m lam) * (lam / 2) =
      admissibleScalarDriftKernel m lam := by
  have hkint := admissible_kernel_integrable hm hlam
  have hdint := admissible_deriv_kernel_integrable hm hlam
  have hbd := admissible_boundary_decay hm hlam
  have hexpAC (T : ℝ) (hT : 0 ≤ T) :
      AbsolutelyContinuousOnInterval (fun s : ℝ => Real.exp (lam * s)) 0 T := by
    apply (continuous_const.mul continuous_id).exp.absolutelyContinuousOnInterval_of_deriv_le
      (C := |lam| * Real.exp (|lam| * T))
    · positivity
    · intro x hx
      have hx0 : 0 ≤ x := by simpa [uIcc_of_le hT] using hx.1
      have hxT : x ≤ T := by simpa [uIcc_of_le hT] using hx.2
      have hder : deriv (fun s : ℝ => Real.exp (lam * s)) x = lam * Real.exp (lam * x) := by
        simpa using (Real.hasDerivAt_exp (lam * x)).comp x (hasDerivAt_const x lam).mul_const
      rw [hder, Real.norm_eq_abs, abs_mul]
      have he : Real.exp (lam * x) ≤ Real.exp (|lam| * T) := by
        apply Real.exp_le_exp.mpr
        have hlamabs : lam ≤ |lam| := le_abs_self lam
        nlinarith
      calc
        |lam| * |Real.exp (lam * x)| = |lam| * Real.exp (lam * x) := by
          rw [abs_of_pos (Real.exp_pos _)]
        _ ≤ |lam| * Real.exp (|lam| * T) :=
          mul_le_mul_of_nonneg_left he (abs_nonneg _)
  have hfinite (T : ℝ) (hT : 0 ≤ T) :
      (∫ s in (0 : ℝ)..T, m s * (lam * Real.exp (lam * s))) =
        m T * Real.exp (lam * T) - m 0 -
          ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (lam * s) := by
    have hip := (hm.localAC T hT).integral_mul_deriv_eq_deriv_mul (hexpAC T hT)
    simpa [mul_assoc] using hip
  have hleft : Tendsto
      (fun T => ∫ s in (0 : ℝ)..T, m s * (lam * Real.exp (lam * s))) atTop
      (𝓝 (lam * admissibleScalarKernel m lam)) := by
    have hi : IntegrableOn (fun s => m s * (lam * Real.exp (lam * s))) (Ioi 0) := by
      simpa [mul_assoc, mul_left_comm, mul_comm] using hkint.const_mul lam
    have ht := intervalIntegral_tendsto_integral_Ioi
      (f := fun s => m s * (lam * Real.exp (lam * s))) 0 hi tendsto_id
    convert ht using 1
    rw [admissibleScalarKernel, ← MeasureTheory.integral_const_mul]
    apply MeasureTheory.integral_congr_ae
    filter_upwards with s
    ring
  have hrightInt : Tendsto
      (fun T => ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (lam * s)) atTop
      (𝓝 (∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (lam * s))) :=
    intervalIntegral_tendsto_integral_Ioi 0 hdint tendsto_id
  have heq_event : ∀ᶠ T in atTop,
      (∫ s in (0 : ℝ)..T, m s * (lam * Real.exp (lam * s))) =
        m T * Real.exp (lam * T) - m 0 -
          ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (lam * s) := by
    filter_upwards [eventually_ge_atTop (0 : ℝ)] with T hT
    exact hfinite T hT
  have hlimrhs := (hbd.sub_const (m 0)).sub hrightInt
  have hlimlhs : Tendsto
      (fun T => m T * Real.exp (lam * T) - m 0 -
          ∫ s in (0 : ℝ)..T, deriv m s * Real.exp (lam * s)) atTop
      (𝓝 (0 - m 0 - ∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (lam * s))) := hlimrhs
  have hlim := hleft.congr' heq_event
  have hscalar : lam * admissibleScalarKernel m lam =
      -m 0 - ∫ s in Ioi (0 : ℝ), deriv m s * Real.exp (lam * s) := by
    have huniq := tendsto_nhds_unique hlim hlimlhs
    linarith
  rw [admissibleScalarDriftKernel]
  nlinarith

/-- Arbitrary-weight Kossakowski kernel on a finite family of downward frequencies. -/
def admissibleKernelMatrix (m : ℝ → ℝ) (ω : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => (admissibleScalarKernel m (ω i + ω j) : ℂ)

/-- Arbitrary-weight drift kernel after integration by parts. -/
def admissibleDriftKernelMatrix (m : ℝ → ℝ) (ω : ι → ℝ) : Matrix ι ι ℂ :=
  fun i j => (admissibleScalarDriftKernel m (ω i + ω j) : ℂ)

/-- Entrywise scalar integration by parts, in the complex coefficient form needed by the
operator theorem. -/
theorem admissible_kernel_drift_coeff
    {ε : ℝ} {m : ℝ → ℝ} {ω : ι → ℝ}
    (hm : AdmissibleWeightData ε m) (hdown : ∀ i, ω i ≤ -ε) :
    ∀ i j,
      admissibleKernelMatrix m ω i j * (((ω i : ℂ) + (ω j : ℂ)) / 2) =
        - admissibleDriftKernelMatrix m ω i j := by
  intro i j
  have hsum : ω i + ω j ≤ -2 * ε := by linarith [hdown i, hdown j]
  have h := admissible_scalar_drift_identity hm hsum
  exact_mod_cast h

/-- The arbitrary admissible-weight drift matrix is positive semidefinite.
The proof obligation is isolated here while the scalar integration-by-parts layer is checked. -/
theorem admissibleDriftKernelMatrix_posSemidef
    {ε : ℝ} {m : ℝ → ℝ} {ω : ι → ℝ}
    (hm : AdmissibleWeightData ε m) (hdown : ∀ i, ω i ≤ -ε) :
    (admissibleDriftKernelMatrix m ω).PosSemidef := by
  sorry

/-- Exact arbitrary-admissible-weight Lyapunov theorem for one finite Bohr family. -/
theorem admissibleKernel_correlatedAdjoint_energy
    {H : QMatrix d} {ε : ℝ} {m : ℝ → ℝ} {ω : ι → ℝ} {A : ι → QMatrix d}
    (hm : AdmissibleWeightData ε m)
    (hH : H.IsHermitian)
    (hA : ∀ i, IsBohrComponent H (A i) (ω i))
    (hdown : ∀ i, ω i ≤ -ε) :
    correlatedAdjoint (fun i j => admissibleKernelMatrix m ω i j) A H =
      - kernelGramOperator (admissibleDriftKernelMatrix m ω) A := by
  exact correlatedAdjoint_eq_neg_kernelGramOperator
    (admissibleKernelMatrix m ω) (admissibleDriftKernelMatrix m ω)
    hH hA (admissible_kernel_drift_coeff hm hdown)

/-- Arbitrary admissible weights give a negative-semidefinite energy drift. -/
theorem admissibleKernel_correlatedAdjoint_energy_nonpos
    {H : QMatrix d} {ε : ℝ} {m : ℝ → ℝ} {ω : ι → ℝ} {A : ι → QMatrix d}
    (hm : AdmissibleWeightData ε m)
    (hH : H.IsHermitian)
    (hA : ∀ i, IsBohrComponent H (A i) (ω i))
    (hdown : ∀ i, ω i ≤ -ε) :
    correlatedAdjoint (fun i j => admissibleKernelMatrix m ω i j) A H ≤ 0 := by
  rw [admissibleKernel_correlatedAdjoint_energy hm hH hA hdown]
  have hK := kernelGramOperator_posSemidef
    (admissibleDriftKernelMatrix m ω) A
    (admissibleDriftKernelMatrix_posSemidef hm hdown)
  rw [Matrix.le_iff]
  simpa using hK

end

end GapFreeLindblad
end FTDQE
